
sonar.projectKey=WilDevFull_SystemDrawn-backend-chore-sonarqube-cloud
sonar.organization=wildevfull
sonar.projectName=SystemDrawn Backend
sonar.projectVersion=1.0.0


sonar.sources=src


sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js


sonar.exclusions=**/.env*,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,vercel.json,.babelrc


sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8